### ISSUE TITLE
Feature request: add `update_frequency` field

### ISSUE THREAD

**Issue by billgeo** [linz/stac#158]
**Is your feature request related to a problem? Please describe.**

Add an `update_frequency` field to the linz extension to allow users to capture this information consistently.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

name: `linz:update_frequency` 
description: "Indicates how frequently an updated dataset may be distributed to the publication platform."
Type: string/enum
One of: "continual", "daily", "weekly", "fortnightly", "monthly", "quarterly", "biannually", "annually", "as needed", "irregular", "not planned".

See https://confluence.linz.govt.nz/display/LIFFP/Core+and+Spatial+Metadata+Content

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**
[Add any other context or screenshots about the feature request here.]

**Comment by l0b0** [comment]
Would it be possible to use machine readable values for the well-defined values, like  [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations)/RFC 3339`P1Y` for "annually"?
