### ISSUE TITLE
Feature request: add 'language' fields for assets

### ISSUE THREAD

**Issue by billgeo** [linz/stac#161]
**Is your feature request related to a problem? Please describe.**

So that a user has some additional information about the assets, we want to add the language used in the dataset, ~~and also the character set encoding of the data~~

Note: after discussion on [Slack](https://linz.slack.com/archives/CN7F6HP2Q/p1637104386119600) decided to leave out character set info for now as it is assumed all LINZ data will be in UTF-8. Enforcing this will be done by the Data Management COP / practice lead. Also decided to use IETF codes for languages/locales rather than ISO standards.

**Describe the solution you'd like**

#### Language
Location: Assets
Name: `linz:language`
Description: "The language code and local of the language used in the data. For example, `en_NZ` for New Zealand English."
Type: "Recommended for internal data. Mandatory for published data."
Restrictions: "Use [IETF rfc 5646](https://datatracker.ietf.org/doc/html/rfc5646) for enum list. Precompiled lists [1](https://gist.github.com/msikma/8912e62ed866778ff8cd) and [2](https://datahub.io/core/language-codes)"

#### Character set

~~Location: inside the `asset` object (can either be in item or collection)
Name: `linz:character_set`
Description: "Character encoding standard used for the data asset."
Type: "Recommended for internal data. Mandatory for published data."
Restrictions: UTF-8 only ~~

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

**Additional context**
[Add any other context or screenshots about the feature request here.]

**Comment by l0b0** [comment]
Why those specific standards? In my experience [IETF language codes](https://en.wikipedia.org/wiki/Language_code) are much more common than ISO 639-2, and UTF-8 is much more common than ISO/IEC 10646:2020.

**Comment by l0b0** [comment]
We might want to use the word ["encoding" rather than "character set"](https://stackoverflow.com/questions/2281646/whats-the-difference-between-encoding-and-charset).

**Comment by billgeo** [comment]
@l0b0 just noticed that your PR for this had this as a required property. It's supposed to be optional. Can you please do another PR to resolve that?

**Comment by billgeo** [comment]
Closing
