### ISSUE TITLE
Feature request: Add automated tests to stac-node-validator

### ISSUE THREAD

**Issue by l0b0** [linz/stac#169]
**Is your feature request related to a problem? Please describe.**

It would be good to make sure `stac-node-validator` is in a healthy state and being maintained.

**Describe the solution you'd like**

- [x] [Add Dependabot support
](https://github.com/stac-utils/stac-node-validator/pull/14)
- [x] [Add automated tests](https://github.com/stac-utils/stac-node-validator/issues/20)

**Describe alternatives you've considered**

We could leave this up to the stac-node-validator maintainers.

**Additional context**

[Test PRs are welcome](https://github.com/stac-utils/stac-node-validator/pull/14#issuecomment-972018243).

**Comment by billgeo** [comment]
This looks good from what I can tell. And after discusison wtih @l0b0
