### ISSUE TITLE
Duplicate validations of collection title property.

### ISSUE THREAD

**Issue by billgeo** [linz/stac#22]
Is this 

https://github.com/linz/STAC/blob/49aaf21177ba8f932967ab0e6beeeed1237967f2/extensions/quality/json-schema/schema.json#L12-L20

a duplicate of this? Should it be removed from the `quality`extension?

https://github.com/linz/STAC/blob/49aaf21177ba8f932967ab0e6beeeed1237967f2/extensions/linz/json-schema/schema.json#L13-L20

**Comment by l0b0** [comment]
It does look like that field doesn't belong in the quality schema - it's basically just making an optional field mandatory, which presumably has nothing to do with the quality of the dataset.

**Comment by billgeo** [comment]
Yeah, we decided it fitted the best in the 'top-level' LINZ extension.

**Comment by billgeo** [comment]
Looks good. Thanks @MitchellPaff
